---
AWSTemplateFormatVersion: "2010-09-09"
Description: AWS VPC CloudFormation Stack
Resources:
  rRDSInstanceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RescaleSecret
      Description: 'This is the secret for my RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        PasswordLength: 21
        ExcludePunctuation: true
  rDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: Subnet group for RDS DB
      DBSubnetGroupName: DBSubnetGroup
      SubnetIds:
        - !ImportValue VPC-SubnetBPrivate
        - !ImportValue VPC-SubnetAPrivate
      Tags:
        - Key: Name
          Value: RDS Subnet Group
  rRds:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceClass: db.t2.micro
      VPCSecurityGroups:
        - !ImportValue VPC-DBServerSG
      DBSubnetGroupName: !Ref rDBSubnetGroup
      DBInstanceIdentifier: rescalepg
      DBName: rescale
      DeleteAutomatedBackups: false
      DeletionProtection: true
      Engine: postgres
      EngineVersion: 11.1
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref rRDSInstanceSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref rRDSInstanceSecret, ':SecretString:password}}' ]]
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: false
      StorageType: standard
      Tags:
        - Key: Name
          Value: RDS PG instance - Do not Delete
